# Generated by Django 5.2.8 on 2025-11-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.URLField(),
        ),
    ]
